In [ ]:
import numpy as np


In [ ]:
list1=[1,2,3,4,5,6,7,8]


In [ ]:
list2=["sooraj",26,]


In [ ]:
type(list1)


<class 'list'>


In [ ]:
type(list2)


<class 'list'>


In [ ]:
type(a)


Traceback (most recent call last):
  File "c:\Users\USER\.vscode\extensions\ms-python.python-2024.10.0-win32-x64\python_files\python_server.py", line 117, in exec_user_input
    retval = callable(user_input, user_globals)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
NameError: name 'a' is not defined



In [ ]:
a=np.array(list1)


In [ ]:
type(a)


<class 'numpy.ndarray'>


In [ ]:
b=np.array(list2)


In [ ]:
type(b)


<class 'numpy.ndarray'>


In [ ]:
a


[1 2 3 4 5 6 7 8]


In [ ]:
b


['sooraj' '26']


In [ ]:
dir(a)


['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__',

In [ ]:
dir(b)


['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__',

In [ ]:
a=np.array(list1)


In [ ]:
a(min)


Traceback (most recent call last):
  File "c:\Users\USER\.vscode\extensions\ms-python.python-2024.10.0-win32-x64\python_files\python_server.py", line 117, in exec_user_input
    retval = callable(user_input, user_globals)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
TypeError: 'numpy.ndarray' object is not callable



In [ ]:
a('min')


Traceback (most recent call last):
  File "c:\Users\USER\.vscode\extensions\ms-python.python-2024.10.0-win32-x64\python_files\python_server.py", line 117, in exec_user_input
    retval = callable(user_input, user_globals)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
TypeError: 'numpy.ndarray' object is not callable



In [ ]:
print(min(a))


1


In [ ]:
print(max(a))


8


In [ ]:
print(sum(a))


36


In [ ]:
a.min()


1


In [ ]:
a.max()


8


In [ ]:
a.mean()


4.5


In [ ]:
a.sum()


36


In [ ]:
a.size


8


In [ ]:
a.shape


(8,)


In [ ]:
a=np.array(list1)


In [ ]:
a=np.array(list1)


In [ ]:
a.shape


(8,)


In [ ]:
a=np.array(list1)


In [ ]:
a.size


8


In [ ]:
a.shape


(8,)


In [ ]:
a.reshape(2,4)


[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
list1=[1,2,3,4,5,6,7,8,9,10]


In [ ]:
a=np.array(list1)


In [ ]:
a.shape


(10,)


In [ ]:
a.reshape(2,5)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
a


[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
b


['sooraj' '26']


In [ ]:
list1=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]


In [ ]:
a=np.array(list1)


In [ ]:
a.reshape(2,2,5)


[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]


In [ ]:
a.shape


(20,)


In [ ]:
a.shape=(2,2,5)


In [ ]:
a


[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]
